# Site settings
title: Debugging The Self
description: A personal journey through spirituality, adventures, and productivity
author: Apoorv
email: sharmavapoorv@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://debuggingtheself.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO settings
twitter:
  username: # Add your Twitter username
  card: summary

social:
  name: Apoorv
  links: # Add your social media profiles here

# jekyll-seo-tag settings
webmaster_verifications:
  google: # Add Google verification code
  bing: # Add Bing verification code

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
