# Site settings
title: Debugging The Self
description: A personal journey through spirituality, travel, and productivity
author: Apoorv
email: your.email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sharma-apoorv.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
